module "bigip-gcp" {
  source                  = "./modules/bigip-gcp"
  project                 = var.gcp_project
  region                  = var.gcp_region
  zone                    = var.gcp_zone
  mgmt_cidr               = "10.1.10.0/24"
  external_cidr           = "10.1.20.0/24"
  internal_cidr           = "10.1.30.0/24"
  ssh_user                = "vmg"
  private-key-path        = "~/.ssh/id_rsa"
  external_count          = 1
  external_machine_type   = "f1-micro"
  external_os_image       = "debian-10"
  external_boot_disk_size = "20"
  external_boot_disk_type = "pd-ssd"
  internal_count          = 1
  internal_machine_type   = "f1-micro"
  internal_os_image       = "debian-10"
  internal_boot_disk_size = "20"
  internal_boot_disk_type = "pd-ssd"
}